name: TypeScript Continuous Integration
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: npm install
      run: cd DotnetTemplate.Web && npm install && npm build
    - name: TypeScript Tests
      run: cd DotnetTemplate.Web && npm t
    - name: Lint
      run: cd DotnetTemplate.Web && npm run lint
